CREATE TABLE IF NOT EXISTS covid_vaccinations
(
	iso_code CHAR(4),
    continent VARCHAR(55),
    location VARCHAR(55),
    date CHAR(10),
    new_tests INT,
    total_tests INT,
    total_tests_per_thousand DECIMAL(12,3),
    new_tests_per_thousand DECIMAL(12,3),
    new_tests_smoothed INT,
    new_tests_smoothed_per_thousand DECIMAL(12,3),
    positive_rate DECIMAL(12,4),
    tests_per_case DECIMAL(12,1),
    tests_units VARCHAR(55),
    total_vaccinations INT,
    people_vaccinated INT,
    people_fully_vaccinated INT,
    total_boosters INT,
    new_vaccinations INT,
    new_vaccinations_smoothed INT,
    total_vaccinations_per_hundred DECIMAL(12,2),
    people_vaccinated_per_hunndred DECIMAL(12,2),
    people_fully_vaccinated_per_hundred DECIMAL(12,2),
    total_boosters_per_hundred DECIMAL(12,2),
    new_vaccinations_smoothed_per_million INT,
    new_people_vaccinated_smoothed INT,
    new_people_vaccinated_smoothed_per_hundred DECIMAL(12,3),
    stringency_index DECIMAL(7,2),
    population_density DECIMAL(12,3),
    median_age DECIMAL(3,1),
    aged_65_older DECIMAL(7,3),
    aged_70_older DECIMAL(7,3),
    gdp_per_capita DECIMAL(12,3),
    extreme_poverty DECIMAL(5,1),
    cardiovasc_death_rate DECIMAL(12,3),
    diabetes_prevalence DECIMAL(7,3),
    female_smokers DECIMAL(5,1),
    male_smokers DECIMAL(5,1),
    handwashing_facilities DECIMAL(12,3),
    hospital_beds_per_thousand DECIMAL(5,2),
    life_expectancy DECIMAL(5,2),
    human_development_index DECIMAL(12,3),
    excess_mortality_cumulative_absolute DECIMAL (10,2),
    excess_mortality_cumulative DECIMAL(10,2),
    excess_mortality DECIMAL(10,2),
    excess_mortality_cumulative_per_million DECIMAL(16,8)
);